### ISSUE TITLE
MongoDBコンテナimageが `Build was canceled` で弾かれる

### ISSUE THREAD

**Issue by miolab** [miolab/circleci_nodejs#3]
## 問題となっていること

`mongo` コンテナが `Build was canceled` されて通らない

- 関連branch https://github.com/miolab/circleci_nodejs/pull/2

## 解決したいこと

- `node` と `mongo` の両imageをビルドする
- 具体的に、以下コードの内容をbuild successしたい

```yml
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.9.0  # この1行を除外し、mongoイメージ単独ビルドするパターンも確認済
      - image: mongo:4.2.0
    steps:
      - checkout
      - run: echo "Finish build!"
```

   公式 [Node.js - JavaScript チュートリアル](https://circleci.com/docs/ja/2.0/language-javascript/) 環境構築手順を参考とした

## 状況の詳細

- ローカルでの確認結果は以下の通り

  1.  mongo コンテナ単独ビルドの場合

  ```bash
    .
    .
  The redacted variables listed above will be masked in run step output.====>> Checkout code
  Making checkout directory "/root/project"
  Copying files from "/tmp/_circleci_local_build_repo" to "/root/project"
  Error: /bin/sh: 1: git: not found

  ====>> Finish
    #!/bin/bash -eo pipefail
  echo "Finish build!"
  Finish build!
  Success!
  ```

  - `Success!` してない
　
  2. nodeコンテナと両方ビルドする場合

  ```terminal
  ====>> Finish
    #!/bin/bash -eo pipefail
  echo "Finish build!"
  Finish build!
  Success!
  Step canceled
  ```

  - mongoコンテナのビルドがcancelされる
　
  3. 公式環境構築に準拠

  - config.yml

  ```yml
  version: 2.1 # CircleCI 2.1 を使用します
  jobs: # 一連のステップ
    build: # ワークフローを使用しない実行では、エントリポイントとして `build` ジョブが必要です
      working_directory: ~/mern-starter # ステップが実行されるディレクトリ
      docker: # Docker でステップを実行します

        - image: circleci/node:10.16.3 # このイメージをすべての `steps` が実行されるプライマリ コンテナとして使用します
        - image: mongo:4.2.0 # このイメージをセカンダリ サービス コンテナとして使用します
      steps: # 実行可能コマンドの集合
        - checkout # ソース コードを作業ディレクトリにチェックアウトする特別なステップ
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
        - restore_cache: # 依存関係キャッシュを復元する特別なステップ
            # 依存関係キャッシュについては https://circleci.com/ja/docs/2.0/caching/ をお読みください
            key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
            name: install-npm-wee
            command: npm install
        - save_cache: # 依存関係キャッシュを保存する特別なステップ
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - ./node_modules
        - run: # テストを実行します
            name: test
            command: npm test
        - run: # カバレッジ レポートを実行します
            name: code-coverage
            command: './node_modules/.bin/nyc report --reporter=text-lcov'
        - store_artifacts: # テスト結果をアーティファクトとして保存する特別なステップ
            # アーティファクト (https://circleci.com/ja/docs/2.0/artifacts/) に表示するテスト サマリーをアップロードします 
            path: test-results.xml
            prefix: tests
        - store_artifacts: # アーティファクト (https://circleci.com/ja/docs/2.0/artifacts/) に表示するため
            path: coverage
            prefix: coverage
        - store_test_results: # テスト サマリー (https://circleci.com/ja/docs/2.0/collect-test-data/) に表示するため
            path: test-results.xml
        # デプロイ例については https://circleci.com/ja/docs/2.0/deployment-integrations/ を参照してください
  ```

  - 結果

    - mongoコンテナが `Build was canceled` される点はおなじ
    - Restoring cache エラー
      `error computing cache key: template: cacheKey:1:20: executing "cacheKey" at <checksum "package-lock.json">: error calling checksum: open /home/circleci/mern-starter/package-lock.json: no such file or directory`
    - test エラー
      ```bash
      #!/bin/bash -eo pipefail
      npm test

      npm ERR! code ENOENT
      npm ERR! syscall open
      npm ERR! path /home/circleci/mern-starter/package.json
      npm ERR! errno -2
      npm ERR! enoent ENOENT: no such file or directory, open '/home/circleci/mern-starter/package.json'
      npm ERR! enoent This is related to npm not being able to find a file.
      npm ERR! enoent 

      npm ERR! A complete log of this run can be found in:
      npm ERR!     /home/circleci/.npm/_logs/2020-09-05T00_51_50_155Z-debug.log


      Exited with code exit status 254

      CircleCI received exit code 254
      ```

## 参考

- おそらくこの状況と似ている  
  https://stackoverflow.com/questions/58527269/add-mongodb-to-circle-ci
  - こちらと同様の解決手法を確認したが、うまくはいかなかった
